"""Generates the Sanctuary v2 leaded-glass SVGs into app/themes/sanctuary-v2/ (deterministic; re-run after edits).
   - triplet.svg: the drone card's window. Three stepped lancets (Early English triplet), 6 quarries, dark lead,
     a brass hood. It sits in the card's title row, top-right, and never behind a control.
   - window-glass.svg / window-light.svg / window-lead.svg: the "Before you play" window. Two lancets and a sexfoil
     oculus, irregular hand-cut quarries, each pane its own radial glow; only the light layer breathes.
   python3 design/warmth/sanctuary-v2/windows.py"""
import math, random, os
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', '..', 'app', 'themes', 'sanctuary-v2')
LEAD = '#0c0716'
GLASS = {  # (centre light, edge deep): each pane is a radial glow, lit from its middle like real pot-metal glass
    'ruby': ('#f06a78', '#8e1f36'), 'sapphire': ('#6f93ff', '#22317f'), 'gold': ('#ffd98a', '#b07a2a'),
    'emerald': ('#6fd9a5', '#1d6a4a'), 'amethyst': ('#c39cff', '#55308e'), 'amber': ('#ffb36b', '#a4501f'),
}

def lancet(x0, x1, ys, yb, r_scale=1.0):
    """Pointed (two-centred) arch: springs at ys, apex above; r = r_scale * width."""
    w = x1 - x0; r = r_scale * w; cx = (x0 + x1) / 2
    apex = ys - math.sqrt(r * r - (r - w / 2) ** 2)
    return (f'M{x0:.2f} {yb:.2f}V{ys:.2f}A{r:.2f} {r:.2f} 0 0 1 {cx:.2f} {apex:.2f}'
            f'A{r:.2f} {r:.2f} 0 0 1 {x1:.2f} {ys:.2f}V{yb:.2f}Z'), apex

def grads(used, pre):
    out = []
    for i, (name, fx, fy) in enumerate(used):
        c, e = GLASS[name]
        out.append(f'<radialGradient id="{pre}{i}" cx="{fx:.2f}" cy="{fy:.2f}" r=".8">'
                   f'<stop offset="0" stop-color="{mix(c, e, .2)}"/><stop offset=".6" stop-color="{mix(c, e, .6)}"/>'
                   f'<stop offset="1" stop-color="{e}"/></radialGradient>')
    return ''.join(out)

def mix(a, b, t):
    A = [int(a[i:i + 2], 16) for i in (1, 3, 5)]; B = [int(b[i:i + 2], 16) for i in (1, 3, 5)]
    return '#' + ''.join('%02x' % round(x + (y - x) * t) for x, y in zip(A, B))

# ------------------------------------------------------------------------------------------------ triplet (drone card)
def triplet():
    W, Hh = 100, 44
    L = [(4, 28, 30.5, 42.5, .95), (36, 64, 28, 42.5, .95), (72, 96, 30.5, 42.5, .95)]  # apexes y 10.5 / 4.6 / 10.5
    # each lancet: two quarries split by a slanted lead line (hand-cut, not a grid)
    splits = [((4, 30), (28, 26)), ((36, 24), (64, 29)), ((72, 26), (96, 30))]
    panes = [('sapphire', 'emerald'), ('gold', 'ruby'), ('amethyst', 'sapphire')]
    used, body, lead, clips = [], [], [], []
    for i, ((x0, x1, ys, yb, rs), ((ax, ay), (bx, by)), (top, bot)) in enumerate(zip(L, splits, panes)):
        d, apex = lancet(x0, x1, ys, yb, rs)
        clips.append(f'<clipPath id="t{i}"><path d="{d}"/></clipPath>')
        used.append((top, .5, .62)); used.append((bot, .45, .35))
        gi = len(used) - 2
        body.append(f'<g clip-path="url(#t{i})">'
                    f'<path d="M{x0 - 2} 0H{x1 + 2}V{by}L{ax} {ay}Z" fill="url(#g{gi})"/>'
                    f'<path d="M{x0 - 2} {ay}L{bx + 2} {by}V{Hh}H{x0 - 2}Z" fill="url(#g{gi + 1})"/></g>')
        lead.append(f'<path d="M{ax} {ay}L{bx} {by}" stroke="{LEAD}" stroke-width="1.7"/>')
        lead.append(f'<path d="{d}" fill="none" stroke="{LEAD}" stroke-width="2.2" stroke-linejoin="round"/>')
    # brass hood moulding over the centre lancet, a sill under all three
    r = .95 * 28 + 3; ap = 28 - math.sqrt(r * r - (r - 17) ** 2)  # concentric with the centre lancet, 3 units out
    hood = f'M33 31V28A{r:.2f} {r:.2f} 0 0 1 50 {ap:.2f}A{r:.2f} {r:.2f} 0 0 1 67 28V31'
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {Hh}" preserveAspectRatio="xMaxYMid meet">'
           f'<!-- Sanctuary v2: the drone card window (generated by design/warmth/sanctuary-v2/windows.py). -->'
           f'<defs>{"".join(clips)}{grads(used, "g")}</defs>'
           f'{"".join(body)}{"".join(lead)}'
           f'<path d="{hood}" fill="none" stroke="#e6ba65" stroke-width="1.3" stroke-linecap="round" opacity=".9"/>'
           f'<path d="M1 43.3H99" stroke="#e6ba65" stroke-width="1.3" stroke-linecap="round" opacity=".9"/></svg>')
    open(os.path.join(OUT, 'triplet.svg'), 'w').write(svg)

# ------------------------------------------------------------------------------------------------ the big window
def big():
    rnd = random.Random(7)
    W, Hh = 200, 320
    outer, _ = lancet(12, 188, 150, 320, 1.0)
    lanc = [lancet(22, 96, 152, 320, 1.0), lancet(104, 178, 152, 320, 1.0)]
    palette = ['sapphire'] * 7 + ['ruby'] * 5 + ['gold'] * 4 + ['emerald'] * 2 + ['amethyst'] * 2 + ['amber'] * 2
    used, glass, lead = [], [], []
    for li, (d, apex) in enumerate(lanc):
        x0, x1 = (22, 96) if li == 0 else (104, 178)
        glass.append(f'<clipPath id="c{li}"><path d="{d}"/></clipPath>')
        # irregular rows: y cut points jitter at each edge; each row splits once at a wandering x
        ys = [apex - 2]; y = apex + 30
        while y < 320: ys.append(y); y += rnd.uniform(26, 36)
        ys.append(322)
        cuts = [(ys[0], ys[0])] + [(yy + rnd.uniform(-5, 5), yy + rnd.uniform(-5, 5)) for yy in ys[1:-1]] + [(322, 322)]
        g = []; inner = []
        for r in range(len(cuts) - 1):
            (la, ra), (lb, rb) = cuts[r], cuts[r + 1]
            mx_t = (x0 + x1) / 2 + rnd.uniform(-12, 12); mx_b = (x0 + x1) / 2 + rnd.uniform(-12, 12)
            if r == 0:  # the arch head: one pane
                polys = [[(x0 - 2, la - 40), (x1 + 2, ra - 40), (x1 + 2, rb), (x0 - 2, lb)]]
            else:
                ymt = la + (ra - la) * (mx_t - x0) / (x1 - x0); ymb = lb + (rb - lb) * (mx_b - x0) / (x1 - x0)
                polys = [[(x0 - 2, la), (mx_t, ymt), (mx_b, ymb), (x0 - 2, lb)],
                         [(mx_t, ymt), (x1 + 2, ra), (x1 + 2, rb), (mx_b, ymb)]]
                inner.append(f'<path d="M{mx_t:.1f} {ymt:.1f}L{mx_b:.1f} {ymb:.1f}"/>')
            if r > 0: inner.append(f'<path d="M{x0 - 4:.1f} {la:.1f}L{x1 + 4:.1f} {ra:.1f}"/>')
            for p in polys:
                name = rnd.choice(palette) if r > 0 else ('gold' if li == 0 else 'ruby')
                used.append((name, rnd.uniform(.35, .65), rnd.uniform(.3, .6)))
                pts = ' '.join(f'{x:.1f},{y:.1f}' for x, y in p)
                g.append(f'<polygon points="{pts}" fill="url(#p{len(used) - 1})"/>')
        glass.append(f'<g clip-path="url(#c{li})">{"".join(g)}</g>')
        lead.append(f'<clipPath id="k{li}"><path d="{d}"/></clipPath><g clip-path="url(#k{li})">{"".join(inner)}</g>')
        lead.append(f'<path d="{d}" stroke-width="4"/>')
    # sexfoil oculus: six lobes round a gold heart
    cx, cy, R = 100, 58, 26
    lobes = []
    for k in range(6):
        a = math.radians(k * 60 - 90); lx, ly = cx + 13 * math.cos(a), cy + 13 * math.sin(a)
        used.append(('ruby' if k % 2 else 'sapphire', .5, .5))
        lobes.append(f'<circle cx="{lx:.1f}" cy="{ly:.1f}" r="10.5" fill="url(#p{len(used) - 1})"/>')
        lead.append(f'<circle cx="{lx:.1f}" cy="{ly:.1f}" r="10.5" stroke-width="2.2"/>')
    used.append(('gold', .45, .4))
    heart = f'<circle cx="{cx}" cy="{cy}" r="7.5" fill="url(#p{len(used) - 1})"/>'
    lead.append(f'<circle cx="{cx}" cy="{cy}" r="7.5" stroke-width="2.2"/><circle cx="{cx}" cy="{cy}" r="{R}" stroke-width="3.5"/>')
    spandrel = '#140c24'
    gsvg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {Hh}" preserveAspectRatio="xMidYMid meet">'
            f'<!-- Sanctuary v2 "Before you play" window, glass layer (generated by windows.py) -->'
            f'<defs><clipPath id="o"><path d="{outer}"/></clipPath>{grads(used, "p")}</defs>'
            f'<g clip-path="url(#o)"><rect width="{W}" height="{Hh}" fill="{spandrel}"/></g>'
            f'<circle cx="{cx}" cy="{cy}" r="{R}" fill="#1b1030"/>{"".join(lobes)}{heart}{"".join(glass)}</svg>')
    lsvg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {Hh}" preserveAspectRatio="xMidYMid meet">'
            f'<!-- light behind the glass; the only layer that breathes (opacity) -->'
            f'<defs><clipPath id="o"><path d="{outer}"/></clipPath>'
            f'<radialGradient id="l" cx="100" cy="130" r="190" gradientUnits="userSpaceOnUse">'
            f'<stop offset="0" stop-color="#fff0cc" stop-opacity=".38"/><stop offset=".5" stop-color="#ffd98a" stop-opacity=".1"/>'
            f'<stop offset="1" stop-color="#ffd98a" stop-opacity="0"/></radialGradient></defs>'
            f'<g clip-path="url(#o)"><rect width="{W}" height="{Hh}" fill="url(#l)"/></g></svg>')
    dsvg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {Hh}" preserveAspectRatio="xMidYMid meet" fill="none">'
            f'<!-- lead came and the brass frame -->'
            f'<g stroke="{LEAD}" stroke-width="2.4" stroke-linejoin="round" stroke-linecap="round">{"".join(lead)}</g>'
            f'<path d="{outer}" stroke="#e6ba65" stroke-width="3" stroke-linejoin="round"/>'
            f'<path d="M4 320V148A184 184 0 0 1 100 0M196 320V148A184 184 0 0 0 100 0" stroke="#e6ba6540" stroke-width="1.5"/>'
            f'<path d="M4 319h192" stroke="#e6ba65" stroke-width="3"/></svg>')
    for n, s in (('window-glass', gsvg), ('window-light', lsvg), ('window-lead', dsvg)):
        open(os.path.join(OUT, f'{n}.svg'), 'w').write(s)

if __name__ == '__main__':
    triplet(); big()
    for f in sorted(os.listdir(OUT)):
        if f.endswith('.svg'): print(f, os.path.getsize(os.path.join(OUT, f)))
